---
- hosts: all
  become : True
  tasks:
    - name: Install python pip
      yum : 
        name: python pip
        state: present

    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name:
      docker_container:
        name: my-app
        image: zouhair1234/my-app:0.0.1
        state: started
        published_ports:
          - 0.0.0.0:8080:8080